# Generated by Django 5.0.4 on 2024-05-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('in_progress', 'In Progress'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='received', max_length=20),
        ),
    ]
