# Generated by Django 5.0.4 on 2024-05-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('in_progress', 'In Progress'), ('in_transit', 'In Transit'), ('complete', 'Complete')], default='received', max_length=20),
        ),
    ]
