# Generated by Django 5.0.4 on 2024-05-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_order_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='feedback',
        ),
        migrations.AddField(
            model_name='order',
            name='feedback_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
