# Generated by Django 5.0.4 on 2024-05-06 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_remove_order_feedback_order_feedback_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
    ]
